import Head from 'next/head'
import Sidebar from '@/comps/sidebar'
import styles from '../styles/Home.module.css'
import Cards from '@/comps/cards'

export default function Home() {

  const items = [
    {
      type : 'male',
      hoodies : [

      ],
      jackets : [

      ],
      headgear : [

      ],
    },
    {
      type : 'female',
      hoodies : [

      ],
      jackets : [

      ],
      headgear : [

      ],
    },
    {
      type : 'unisex',
      hoodies : [

      ],
      jackets : [

      ],
      headgear : [

      ],
    },
  ]


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar />
        <Cards />
      </main>
    </>
  )
}
